apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: config-service
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "1280Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
        env:
          - name: BPL_JVM_THREAD_COUNT
            value: "50"
        lifecycle: 
            preStop:                    
              exec: 
                command: [ "sh", "-c", "sleep 5" ] 
